/**
 * Generates a clean Markdown SEO report from page scan result.
 * @param {Object} scanResult
 * @param {Array} issues
 * @param {Object} counts
 * @returns {string}
 */
export function generateSeoReport(scanResult, issues = [], counts = {}) {
  if (!scanResult) return 'No scan data available.';

  const { page, meta, headingsCounts, headings, imagesCounts, linksCounts, social, structuredData } = scanResult;

  const lines = [
    `# META SEO Checker Report`,
    ``,
    `**URL:** ${page?.url || 'Unknown'}`,
    `**Date:** ${new Date().toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## SEO Health Overview`,
    `- ❌ **Errors:** ${counts.error || 0}`,
    `- ⚠️ **Warnings:** ${counts.warning || 0}`,
    `- ✅ **Passed:** ${counts.passed || 0}`,
    ``,
    `---`,
    ``,
    `## Meta Information`,
    `- **Title:** ${meta?.title || '(None)'} (${meta?.titleLength || 0} characters)`,
    `- **Description:** ${meta?.description || '(None)'} (${meta?.descriptionLength || 0} characters)`,
    `- **Keywords:** ${meta?.keywords?.length ? meta.keywords.join(', ') : '(None)'}`,
    `- **Canonical:** ${meta?.canonical || '(None)'}`,
    `- **Robots:** ${meta?.robots?.summaryText || 'Default'}`,
    `- **Language:** ${meta?.lang || '(Missing)'}`,
    `- **Charset:** ${meta?.charset || '(Missing)'}`,
    `- **Viewport:** ${meta?.viewport || '(Missing)'}`,
    ``,
    `---`,
    ``,
    `## Headings`,
    `- **H1:** ${headingsCounts?.h1 || 0}`,
    `- **H2:** ${headingsCounts?.h2 || 0}`,
    `- **H3:** ${headingsCounts?.h3 || 0}`,
    `- **H4:** ${headingsCounts?.h4 || 0}`,
    `- **H5:** ${headingsCounts?.h5 || 0}`,
    `- **H6:** ${headingsCounts?.h6 || 0}`,
    `- **Total:** ${headingsCounts?.total || 0}`,
    headings && headings.filter(h => h.level === 1).length > 0
      ? `\n**H1 Tags:**\n${headings.filter(h => h.level === 1).map(h => `  - "${h.text || '(empty)'}"`).join('\n')}`
      : ``,
    ``,
    `---`,
    ``,
    `## Images`,
    `- **Total Images:** ${imagesCounts?.total || 0}`,
    `- **Missing ALT:** ${imagesCounts?.missingAlt || 0}`,
    `- **Empty ALT (alt=""):** ${imagesCounts?.emptyAlt || 0}`,
    `- **Missing Title:** ${imagesCounts?.missingTitle || 0}`,
    `- **Lazy Loaded:** ${imagesCounts?.lazyLoaded || 0}`,
    ``,
    `---`,
    ``,
    `## Links`,
    `- **Total Links:** ${linksCounts?.total || 0}`,
    `- **Unique URLs:** ${linksCounts?.unique || 0}`,
    `- **Internal:** ${linksCounts?.internal || 0}`,
    `- **External:** ${linksCounts?.external || 0}`,
    `- **Anchors:** ${linksCounts?.anchor || 0}`,
    `- **NoFollow:** ${linksCounts?.nofollow || 0}`,
    `- **Sponsored:** ${linksCounts?.sponsored || 0}`,
    `- **UGC:** ${linksCounts?.ugc || 0}`,
    ``,
    `---`,
    ``,
    `## Social & Structured Data`,
    `- **Open Graph:** ${social?.openGraph?.hasOg ? `Detected (${social.openGraph.items.length} tags)` : 'None'}`,
    social?.openGraph?.title ? `  - **og:title:** ${social.openGraph.title}` : '',
    social?.openGraph?.image ? `  - **og:image:** ${social.openGraph.image}` : '',
    `- **Twitter Card:** ${social?.twitter?.hasTwitter ? `Detected (${social.twitter.card || 'configured'})` : 'None'}`,
    social?.twitter?.title ? `  - **twitter:title:** ${social.twitter.title}` : '',
    `- **JSON-LD Blocks:** ${structuredData?.jsonLd?.total || 0}`,
    `- **Microdata:** ${structuredData?.microdata?.hasMicrodata ? `Detected (${structuredData.microdata.types.join(', ') || 'Schema.org'})` : 'None'}`,
    ``,
    `---`,
    ``,
    `## Detected Issues & Recommendations`,
  ];

  if (!issues || issues.length === 0) {
    lines.push(`No specific issues detected.`);
  } else {
    issues.forEach(issue => {
      const icon = issue.severity === 'error' ? '❌' : issue.severity === 'warning' ? '⚠️' : issue.severity === 'passed' ? '✅' : 'ℹ️';
      lines.push(`${icon} **[${issue.severity.toUpperCase()}] ${issue.title}**`);
      lines.push(`  ${issue.description}`);
      if (issue.value) lines.push(`  *Value:* ${issue.value}`);
      lines.push(``);
    });
  }

  lines.push(`---`);
  lines.push(`*Generated by META SEO Checker extension*`);

  return lines.filter(line => line !== undefined).join('\n');
}
